version: '2'
services:
  nginx:
    container_name: nginx
    image: nginx
    volumes:
    - ../project:/www
    - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
    - "8090:80"
    networks:
      app_net:
        ipv4_address: 172.16.238.100
  php:
    container_name: php7
    image: subdee/php7-mongo
    volumes:
    - ../project:/www:rw
    - ./php/php-fpm.conf:/usr/local/etc/php-fpm.conf
    - ./php/php.ini:/usr/local/etc/php/php.ini
    working_dir: /www/
    environment:
    - ICU_DATA=/opt/icu/
    - DB_HOST=mariadb
    - DB_USER=root
    - DB_PASSWORD=dev
    - MONGO_HOST=mongodb
    - MONGO_USER=
    - MONGO_PASSWORD=
    networks:
      app_net:
        ipv4_address: 172.16.238.110
  mongo:
    container_name: mongodb
    image: mongo
    volumes:
    - ./mongo/db:/data/db:rw
    - ./mongo/mongod.conf:/etc/mongodb.conf
    command: "mongod --config /etc/mongodb.conf"
    networks:
      app_net:
        ipv4_address: 172.16.238.8
  mariadb:
    container_name: mariadb
    image: mariadb
    volumes:
    - ./mariadb/db:/var/lib.mysql:rw
    - ./mariadb/conf.d:/etc/mysql/conf.d
    environment:
    - MYSQL_ROOT_PASSWORD=dev
    - MYSQL_DATABASE=test
    networks:
      app_net:
        ipv4_address: 172.16.238.120
